name: Build and Release for All Platforms

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  # 1) Build on Ubuntu for Linux & Windows
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build for Linux
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/idle-game-linux-amd64

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o dist/idle-game-windows-amd64.exe

      - name: Upload Linux & Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-windows
          path: dist  # Upload all files in 'dist'

  # 2) Build on macOS for Darwin
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build for macOS
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=amd64 go build -o dist/idle-game-darwin-amd64

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac
          path: dist

  # 3) Create the Release and Upload All Binaries
  create_release:
    runs-on: ubuntu-latest
    needs: [build_ubuntu, build_macos]
    steps:
      - name: Download Linux & Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-windows
          path: dist

      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: mac
          path: dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          release_name: "Automated Build #${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/idle-game-windows-amd64.exe
          asset_name: "idle-game-windows-amd64.exe"
          asset_content_type: application/octet-stream

      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/idle-game-linux-amd64
          asset_name: "idle-game-linux-amd64"
          asset_content_type: application/octet-stream

      - name: Upload macOS Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/idle-game-darwin-amd64
          asset_name: "idle-game-darwin-amd64"
          asset_content_type: application/octet-stream
