name: Build and Release All Platforms

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o dist/idle-game-windows-amd64.exe

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/idle-game-linux-amd64

      - name: Build for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o dist/idle-game-darwin-amd64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          # We'll name the tag with the GitHub Actions run number to avoid collisions
          tag_name: build-${{ github.run_number }}
          release_name: "Automated Build #${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/idle-game-windows-amd64.exe
          asset_name: "idle-game-windows-amd64.exe"
          asset_content_type: application/octet-stream

      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/idle-game-linux-amd64
          asset_name: "idle-game-linux-amd64"
          asset_content_type: application/octet-stream

      - name: Upload macOS Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/idle-game-darwin-amd64
          asset_name: "idle-game-darwin-amd64"
          asset_content_type: application/octet-stream
